// Generated by CoffeeScript 1.6.3
(function() {
  var file, static_server;

  static_server = require('node-static');

  file = new static_server.Server('./node_modules/grunt-docular/node_modules/docular/lib/generated');

  require('http').createServer(function(request, response) {
    return request.addListener('end', function() {
      return file.serve(request, response);
    }).resume();
  }).listen(8080);

}).call(this);

/*
//@ sourceMappingURL=doc.map
*/
